# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.13.2
    command: >
      bash -c "gem install observer ostruct --no-document &&
               bundle install --no-cache &&
               /tmp/entry_point.sh"
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
